#
# file: .travis.yml
#
# author: Copyright (C) 2015-2017 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# use "trusty", container-based infrastructure
dist: trusty
sudo: false

# texinfo is needed to build bleeding-edge-toolchain
addons:
    apt:
        packages:
            - texinfo
            - texlive

# use minimal environment
language: generic

matrix:
    include:
        - env: SUBSTAGE="build 5"
        - env: SUBSTAGE="build 6"
        - env: SUBSTAGE="build 7"

install:
    - "./distortos/scripts/travis-ci.sh install ${SUBSTAGE}"

script:
    - "./distortos/scripts/travis-ci.sh script ${SUBSTAGE} configurations"
