#
# file: .travis.yml
#
# author: Copyright (C) 2015-2019 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

dist: xenial
sudo: required

addons:
    apt:
        packages:
            - ninja-build

# use minimal environment
language: generic

matrix:
    include:
        - env: SUBSTAGE="build 5"
        - env: SUBSTAGE="build 6"
        - env: SUBSTAGE="build 7"
        - env: SUBSTAGE="build 8"
        - env: SUBSTAGE="build 9"

install:
    - "./distortos/scripts/travis-ci.sh install ${SUBSTAGE}"

script:
    - "./distortos/scripts/travis-ci.sh script ${SUBSTAGE} configurations"
